<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Aggregates\BandAggregate\Events\"/>
        <Folder Include="Aggregates\BandAggregate\ValueObjects\"/>
        <Folder Include="Aggregates\BookingAgencyAggregate\Events\"/>
        <Folder Include="Aggregates\ClientAggregate\Events\"/>
        <Folder Include="Aggregates\ClientAggregate\ValueObjects\"/>
        <Folder Include="Aggregates\EventAggregate\Events\"/>
        <Folder Include="Aggregates\EventAggregate\ValueObjects\"/>
        <Folder Include="Aggregates\PromoterAgencyAggregate\Events\"/>
        <Folder Include="Aggregates\SponsorAggregate\Events\"/>
        <Folder Include="Aggregates\TicketAgencyAggregate\Events\"/>
        <Folder Include="Aggregates\TicketPoolAggregate\Events\"/>
        <Folder Include="Aggregates\TicketPoolAggregate\ValueObjects\"/>
        <Folder Include="Aggregates\UserAggregate\Events\"/>
        <Folder Include="Aggregates\UserAggregate\ValueObjects\"/>
        <Folder Include="Aggregates\VenueAggregate\Events\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Identity" Version="1.12.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.7"/>
    </ItemGroup>

</Project>
