// <auto-generated />
using System;
using Infrastructure_EF_SQLdB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure_EF_SQLdB.Migrations.Club25Clients
{
    [DbContext(typeof(Club25ClientsContext))]
    [Migration("20240918113830_small-RF")]
    partial class smallRF
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Club25_Domain.Aggregates.ClientAggregate.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchasedate")
                        .HasColumnOrder(2);

                    b.Property<string>("PurchaseStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purchasestatus")
                        .HasColumnOrder(1);

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticketid")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Purchase", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Common.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<decimal>("ConfigVersion")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("configversion")
                        .HasColumnOrder(7);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("email")
                        .HasColumnOrder(4);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("login")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name")
                        .HasColumnOrder(2);

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("pass")
                        .HasColumnOrder(5);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("salt")
                        .HasColumnOrder(6);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("surname")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.ClientAggregate.Client", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.UserAccount");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate")
                        .HasColumnOrder(1);

                    b.Property<string>("FavouriteBandssIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("favouritebandssids")
                        .HasColumnOrder(4);

                    b.Property<string>("FavouriteEventsIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("favouriteeventsids")
                        .HasColumnOrder(3);

                    b.Property<string>("FavouriteVenuesIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("favouritevenuesids")
                        .HasColumnOrder(2);

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("phone")
                        .HasColumnOrder(0);

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.ClientAggregate.Entities.Purchase", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.ClientAggregate.Client", "Client")
                        .WithMany("Purchases")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.ClientAggregate.Client", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
