// <auto-generated />
using System;
using Infrastructure_EF_SQLdB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure_EF_SQLdB.Migrations
{
    [DbContext(typeof(Club25Context))]
    [Migration("20240905091314_revert-RF")]
    partial class revertRF
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistBand", b =>
                {
                    b.Property<int>("BandsId")
                        .HasColumnType("int");

                    b.Property<int>("MembersId")
                        .HasColumnType("int");

                    b.HasKey("BandsId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("ArtistBand");
                });

            modelBuilder.Entity("ArtistTag", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("ArtistsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ArtistTag");
                });

            modelBuilder.Entity("BandTag", b =>
                {
                    b.Property<int>("BandsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("BandsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BandTag");
                });

            modelBuilder.Entity("BookerBookingAgencyBand", b =>
                {
                    b.Property<int>("BandsId")
                        .HasColumnType("int");

                    b.Property<int>("BookersId")
                        .HasColumnType("int");

                    b.HasKey("BandsId", "BookersId");

                    b.HasIndex("BookersId");

                    b.ToTable("BookerBookingAgencyBand");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BandAggregate.Band", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Band", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BandAggregate.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PriceId")
                        .HasColumnType("int");

                    b.Property<int?>("PriceId1")
                        .HasColumnType("int");

                    b.Property<string>("StageName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("stagename");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PriceId");

                    b.HasIndex("PriceId1");

                    b.ToTable("Artist", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BookingAgencyAggregate.Entities.BookingAgencyBand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<int>("BookingAgencyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("BookingAgencyId");

                    b.ToTable("BookingAgencyBand", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.ClientAggregate.Client", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int")
                        .HasColumnName("id_person");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.ClientAggregate.Entities.PersonObsolete", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Culture", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("IdCurrency")
                        .HasColumnType("int")
                        .HasColumnName("idCurrency");

                    b.Property<int>("IdLanguage")
                        .HasColumnType("int")
                        .HasColumnName("idLanguage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("shortName");

                    b.HasKey("Id");

                    b.HasIndex("IdCurrency");

                    b.HasIndex("IdLanguage");

                    b.ToTable("Culture", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("name");

                    b.Property<string>("Shortname")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("shortname");

                    b.HasKey("Id");

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.EventArtist", b =>
                {
                    b.Property<int>("IdArtist")
                        .HasColumnType("int")
                        .HasColumnName("idArtist");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.HasIndex("IdArtist");

                    b.HasIndex("IdEvent");

                    b.ToTable("EventArtist", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.EventDescription", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int>("IdLanguage")
                        .HasColumnType("int")
                        .HasColumnName("idLanguage");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdLanguage");

                    b.ToTable("EventDescription", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.EventMediaPartner", b =>
                {
                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int>("IdSponsor")
                        .HasColumnType("int")
                        .HasColumnName("idSponsor");

                    b.Property<int?>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdSponsor");

                    b.HasIndex("Price");

                    b.ToTable("EventMediaPartner", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.EventSponsor", b =>
                {
                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int?>("IdPrice")
                        .HasColumnType("int")
                        .HasColumnName("idPrice");

                    b.Property<int>("IdSponsor")
                        .HasColumnType("int")
                        .HasColumnName("idSponsor");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdPrice");

                    b.HasIndex("IdSponsor");

                    b.ToTable("EventSponsor", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.EventTag", b =>
                {
                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int>("IdTag")
                        .HasColumnType("int")
                        .HasColumnName("idTag");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdTag");

                    b.ToTable("EventTag", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.FeaturedEvent", b =>
                {
                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.HasIndex("IdEvent");

                    b.ToTable("FeaturedEvent", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("shortName");

                    b.HasKey("Id");

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Lineup", b =>
                {
                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("description");

                    b.Property<int?>("IdArtist")
                        .HasColumnType("int")
                        .HasColumnName("idArtist");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int?>("IdStage")
                        .HasColumnType("int")
                        .HasColumnName("idStage");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("startTime");

                    b.Property<DateTime>("StopTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("stopTime");

                    b.HasIndex("IdArtist");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdStage");

                    b.ToTable("Lineup", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int>("IdCurrency")
                        .HasColumnType("int")
                        .HasColumnName("idCurrency");

                    b.HasKey("Id");

                    b.HasIndex("IdCurrency");

                    b.ToTable("Price", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("FbEvent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fbEvent");

                    b.Property<byte[]>("Flyer")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("flyer");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("idVenue");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.SponsorAggregate.Entities.MainSponsor", b =>
                {
                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateEnd");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateStart");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<int?>("IdPrice")
                        .HasColumnType("int")
                        .HasColumnName("idPrice");

                    b.Property<int>("IdSponsor")
                        .HasColumnType("int")
                        .HasColumnName("idSponsor");

                    b.HasIndex("IdPrice");

                    b.HasIndex("IdSponsor");

                    b.ToTable("MainSponsor", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.SponsorAggregate.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Details")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("details");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("email");

                    b.Property<byte[]>("Logo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("logo");

                    b.Property<byte[]>("LogoBlack")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("logoBlack");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Www")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("www");

                    b.HasKey("Id");

                    b.ToTable("Sponsor", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("hash");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("idClient");

                    b.Property<int>("IdTicketPool")
                        .HasColumnType("int")
                        .HasColumnName("idTicketPool");

                    b.Property<int?>("SeatNumber")
                        .HasColumnType("int")
                        .HasColumnName("seatNumber");

                    b.Property<DateTime>("SoldDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("soldDate");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdTicketPool");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.TicketMediaType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("TicketMediaType", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("TicketType", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Adres")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("adres");

                    b.Property<decimal?>("AverageProfit")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("averageProfit");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("email");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("phone");

                    b.Property<string>("Www")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("www");

                    b.HasKey("Id");

                    b.ToTable("Vendor", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.TicketPool", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateEnd");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateStart");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int>("IdPrice")
                        .HasColumnType("int")
                        .HasColumnName("idPrice");

                    b.Property<int>("IdTicketMedia")
                        .HasColumnType("int")
                        .HasColumnName("idTicketMedia");

                    b.Property<int>("IdTicketType")
                        .HasColumnType("int")
                        .HasColumnName("idTicketType");

                    b.Property<int>("IdVendor")
                        .HasColumnType("int")
                        .HasColumnName("idVendor");

                    b.Property<decimal?>("Profit")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("profit");

                    b.HasKey("Id");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdPrice");

                    b.HasIndex("IdTicketMedia");

                    b.HasIndex("IdTicketType");

                    b.HasIndex("IdVendor");

                    b.ToTable("TicketPool", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.UserAggregate.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.UserAggregate.Entities.Policy", b =>
                {
                    b.Property<int>("IdPermission")
                        .HasColumnType("int")
                        .HasColumnName("idPermission");

                    b.Property<int>("IdUserGroup")
                        .HasColumnType("int")
                        .HasColumnName("idUserGroup");

                    b.HasIndex("IdPermission");

                    b.HasIndex("IdUserGroup");

                    b.ToTable("Policy", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.UserAggregate.Entities.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("UserGroup", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("number")
                        .HasColumnOrder(1);

                    b.Property<int>("PlanX")
                        .HasColumnType("int")
                        .HasColumnName("planx")
                        .HasColumnOrder(2);

                    b.Property<int>("PlanY")
                        .HasColumnType("int")
                        .HasColumnName("plany")
                        .HasColumnOrder(3);

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("size")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Seat", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity")
                        .HasColumnOrder(2);

                    b.Property<int?>("LinkId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<string>("SectorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sectortype")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("LinkId")
                        .IsUnique()
                        .HasFilter("[LinkId] IS NOT NULL");

                    b.ToTable("Sector", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<int?>("PriceId")
                        .HasColumnType("int");

                    b.Property<int?>("PriceId1")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PriceId");

                    b.HasIndex("PriceId1");

                    b.HasIndex("VenueId");

                    b.ToTable("Stage", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.StageToStageManager", b =>
                {
                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("StageManagerId")
                        .HasColumnType("int");

                    b.HasKey("StageId", "StageManagerId");

                    b.HasIndex("StageManagerId");

                    b.ToTable("StageToStageManager", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Common.Entities.Description", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescriptionText")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("descriptiontext")
                        .HasColumnOrder(1);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("banddescription")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Club25_Domain.Common.Entities.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int?>("BandId")
                        .HasColumnType("int");

                    b.Property<int>("LinkType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("BandId");

                    b.HasIndex("VenueId");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("Club25_Domain.Common.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Club25_Domain.Common.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name")
                        .HasColumnOrder(1);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("surname")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Club25_Domain.Common.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("PromoterAgencyTicketAgency", b =>
                {
                    b.Property<int>("PromoterAgenciesId")
                        .HasColumnType("int");

                    b.Property<int>("TicketAgencyId")
                        .HasColumnType("int");

                    b.HasKey("PromoterAgenciesId", "TicketAgencyId");

                    b.HasIndex("TicketAgencyId");

                    b.ToTable("PromoterAgencyTicketAgency");
                });

            modelBuilder.Entity("PromoterAgencyTicketAgent", b =>
                {
                    b.Property<int>("AccountantsId")
                        .HasColumnType("int");

                    b.Property<int>("PromoterAgenciesId")
                        .HasColumnType("int");

                    b.HasKey("AccountantsId", "PromoterAgenciesId");

                    b.HasIndex("PromoterAgenciesId");

                    b.ToTable("Accountants", (string)null);
                });

            modelBuilder.Entity("SectorStage", b =>
                {
                    b.Property<int>("SectorsId")
                        .HasColumnType("int");

                    b.Property<int>("StagesId")
                        .HasColumnType("int");

                    b.HasKey("SectorsId", "StagesId");

                    b.HasIndex("StagesId");

                    b.ToTable("SectorStage");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BandAggregate.Entities.ArtistDescription", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Description");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.HasIndex("ArtistId");

                    b.ToTable("ArtistDescription", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BandAggregate.Entities.BandDescription", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Description");

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.HasIndex("BandId");

                    b.ToTable("BandDescription", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Common.Entities.LinkDescription", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Description");

                    b.Property<int>("LinkId")
                        .HasColumnType("int");

                    b.HasIndex("LinkId");

                    b.ToTable("LinkDescription", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BookingAgencyAggregate.BookingAgency", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Organization");

                    b.ToTable("BookingAgency", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.PromoterAgencyAggregate.PromoterAgency", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Organization");

                    b.ToTable("PromoterAgency", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketAgencyAggregate.TicketAgency", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Organization");

                    b.ToTable("TicketAgency", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Venue", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Organization");

                    b.Property<decimal?>("GpsLatitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("gpslatitude");

                    b.Property<decimal?>("GpsLongitude")
                        .HasPrecision(18, 15)
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("gpslongitude");

                    b.ToTable("Venue", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BookingAgencyAggregate.Entities.Booker", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Person");

                    b.Property<int>("BookingAgencyId")
                        .HasColumnType("int");

                    b.HasIndex("BookingAgencyId");

                    b.ToTable("Booker", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.PromoterAgencyAggregate.Entities.Promoter", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Person");

                    b.Property<int>("PromoterAgencyId")
                        .HasColumnType("int");

                    b.HasIndex("PromoterAgencyId");

                    b.ToTable("Promoter", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketAgencyAggregate.Entities.TicketAgent", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Person");

                    b.Property<int>("TicketAgencyId")
                        .HasColumnType("int");

                    b.HasIndex("TicketAgencyId");

                    b.ToTable("TicketAgent", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Person");

                    b.Property<int>("IdGroup")
                        .HasColumnType("int")
                        .HasColumnName("id_group");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int")
                        .HasColumnName("id_person");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("password");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdPerson");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.StageManager", b =>
                {
                    b.HasBaseType("Club25_Domain.Common.Entities.Person");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasIndex("VenueId");

                    b.ToTable("StageManager", (string)null);
                });

            modelBuilder.Entity("ArtistBand", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Band", null)
                        .WithMany()
                        .HasForeignKey("BandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtistTag", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Club25_Domain.Common.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BandTag", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Band", null)
                        .WithMany()
                        .HasForeignKey("BandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Club25_Domain.Common.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookerBookingAgencyBand", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BookingAgencyAggregate.Entities.BookingAgencyBand", null)
                        .WithMany()
                        .HasForeignKey("BandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Club25_Domain.Aggregates.BookingAgencyAggregate.Entities.Booker", null)
                        .WithMany()
                        .HasForeignKey("BookersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BandAggregate.Entities.Artist", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Price", null)
                        .WithMany("ArtistIdPriceMaxNavigations")
                        .HasForeignKey("PriceId");

                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Price", null)
                        .WithMany("ArtistIdPriceMinNavigations")
                        .HasForeignKey("PriceId1");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BookingAgencyAggregate.Entities.BookingAgencyBand", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Band", "Band")
                        .WithMany("Bookers")
                        .HasForeignKey("BandId")
                        .IsRequired();

                    b.HasOne("Club25_Domain.Aggregates.BookingAgencyAggregate.BookingAgency", "BookingAgency")
                        .WithMany("Bands")
                        .HasForeignKey("BookingAgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Club25_Domain.Aggregates.BookingAgencyAggregate.ValueObjects.BookingAgencyPriceVO", "PriceMax", b1 =>
                        {
                            b1.Property<int>("BookingAgencyBandId")
                                .HasColumnType("int");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnOrder(4);

                            b1.Property<decimal>("Price")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnOrder(3);

                            b1.HasKey("BookingAgencyBandId");

                            b1.ToTable("BookingAgencyBand");

                            b1.WithOwner()
                                .HasForeignKey("BookingAgencyBandId");
                        });

                    b.OwnsOne("Club25_Domain.Aggregates.BookingAgencyAggregate.ValueObjects.BookingAgencyPriceVO", "PriceMin", b1 =>
                        {
                            b1.Property<int>("BookingAgencyBandId")
                                .HasColumnType("int");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnOrder(2);

                            b1.Property<decimal>("Price")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnOrder(1);

                            b1.HasKey("BookingAgencyBandId");

                            b1.ToTable("BookingAgencyBand");

                            b1.WithOwner()
                                .HasForeignKey("BookingAgencyBandId");
                        });

                    b.Navigation("Band");

                    b.Navigation("BookingAgency");

                    b.Navigation("PriceMax");

                    b.Navigation("PriceMin");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.ClientAggregate.Client", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.ClientAggregate.Entities.PersonObsolete", "IdPersonNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("IdPerson")
                        .IsRequired()
                        .HasConstraintName("FK_Client_Person");

                    b.Navigation("IdPersonNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Culture", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Currency", "IdCurrencyNavigation")
                        .WithMany("Cultures")
                        .HasForeignKey("IdCurrency")
                        .IsRequired()
                        .HasConstraintName("FK_Culture_Currency");

                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Language", "IdLanguageNavigation")
                        .WithMany("Cultures")
                        .HasForeignKey("IdLanguage")
                        .IsRequired()
                        .HasConstraintName("FK_Culture_Language");

                    b.Navigation("IdCurrencyNavigation");

                    b.Navigation("IdLanguageNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.EventArtist", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Entities.Artist", "IdArtistNavigation")
                        .WithMany()
                        .HasForeignKey("IdArtist")
                        .IsRequired()
                        .HasConstraintName("FK_EventArtists_Artist");

                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventArtists_Event");

                    b.Navigation("IdArtistNavigation");

                    b.Navigation("IdEventNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.EventDescription", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventDescription_Event");

                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Language", "IdLanguageNavigation")
                        .WithMany()
                        .HasForeignKey("IdLanguage")
                        .IsRequired()
                        .HasConstraintName("FK_EventDescription_Language");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdLanguageNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.EventMediaPartner", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventMediaPartner_Event");

                    b.HasOne("Club25_Domain.Aggregates.SponsorAggregate.Sponsor", "IdSponsorNavigation")
                        .WithMany()
                        .HasForeignKey("IdSponsor")
                        .IsRequired()
                        .HasConstraintName("FK_EventMediaPartner_Sponsor");

                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Price", "PriceNavigation")
                        .WithMany()
                        .HasForeignKey("Price")
                        .HasConstraintName("FK_EventMediaPartner_Price");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdSponsorNavigation");

                    b.Navigation("PriceNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.EventSponsor", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventSponsor_Event");

                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Price", "IdPriceNavigation")
                        .WithMany()
                        .HasForeignKey("IdPrice")
                        .HasConstraintName("FK_EventSponsor_Price");

                    b.HasOne("Club25_Domain.Aggregates.SponsorAggregate.Sponsor", "IdSponsorNavigation")
                        .WithMany()
                        .HasForeignKey("IdSponsor")
                        .IsRequired()
                        .HasConstraintName("FK_EventSponsor_Sponsor");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdPriceNavigation");

                    b.Navigation("IdSponsorNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.EventTag", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventTag_Event");

                    b.HasOne("Club25_Domain.Common.Entities.Tag", "IdTagNavigation")
                        .WithMany()
                        .HasForeignKey("IdTag")
                        .IsRequired()
                        .HasConstraintName("FK_EventTag_Tag");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdTagNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.FeaturedEvent", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_FeaturedEvents_Event");

                    b.Navigation("IdEventNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Lineup", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Entities.Artist", "IdArtistNavigation")
                        .WithMany()
                        .HasForeignKey("IdArtist")
                        .HasConstraintName("FK_Lineup_Artist");

                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_Lineup_Event");

                    b.HasOne("Club25_Domain.Aggregates.VenueAggregate.Entities.Stage", "IdStageNavigation")
                        .WithMany()
                        .HasForeignKey("IdStage")
                        .HasConstraintName("FK_Lineup_Stage");

                    b.Navigation("IdArtistNavigation");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdStageNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Price", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Currency", "IdCurrencyNavigation")
                        .WithMany("Prices")
                        .HasForeignKey("IdCurrency")
                        .IsRequired()
                        .HasConstraintName("FK_Price_Currency");

                    b.Navigation("IdCurrencyNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.VenueAggregate.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_Event_Venue");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.SponsorAggregate.Entities.MainSponsor", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Price", "IdPriceNavigation")
                        .WithMany()
                        .HasForeignKey("IdPrice")
                        .HasConstraintName("FK_MainSponsor_Price");

                    b.HasOne("Club25_Domain.Aggregates.SponsorAggregate.Sponsor", "IdSponsorNavigation")
                        .WithMany()
                        .HasForeignKey("IdSponsor")
                        .IsRequired()
                        .HasConstraintName("FK_MainSponsor_Sponsor");

                    b.Navigation("IdPriceNavigation");

                    b.Navigation("IdSponsorNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.Ticket", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.ClientAggregate.Client", "IdClientNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Client");

                    b.HasOne("Club25_Domain.Aggregates.TicketPoolAggregate.TicketPool", "IdTicketPoolNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdTicketPool")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_TicketPool");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdTicketPoolNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.TicketPool", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Event", "IdEventNavigation")
                        .WithMany("TicketPools")
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPool_Event");

                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Price", "IdPriceNavigation")
                        .WithMany("TicketPools")
                        .HasForeignKey("IdPrice")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPool_Price");

                    b.HasOne("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.TicketMediaType", "IdTicketMediaNavigation")
                        .WithMany("TicketPools")
                        .HasForeignKey("IdTicketMedia")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPool_TicketMediaType");

                    b.HasOne("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.TicketType", "IdTicketTypeNavigation")
                        .WithMany("TicketPools")
                        .HasForeignKey("IdTicketType")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPool_TicketType");

                    b.HasOne("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.Vendor", "IdVendorNavigation")
                        .WithMany("TicketPools")
                        .HasForeignKey("IdVendor")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPool_Vendor");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdPriceNavigation");

                    b.Navigation("IdTicketMediaNavigation");

                    b.Navigation("IdTicketTypeNavigation");

                    b.Navigation("IdVendorNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.UserAggregate.Entities.Policy", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.UserAggregate.Entities.Permission", "IdPermissionNavigation")
                        .WithMany()
                        .HasForeignKey("IdPermission")
                        .IsRequired()
                        .HasConstraintName("FK_Policy_Permission");

                    b.HasOne("Club25_Domain.Aggregates.UserAggregate.Entities.UserGroup", "IdUserGroupNavigation")
                        .WithMany()
                        .HasForeignKey("IdUserGroup")
                        .IsRequired()
                        .HasConstraintName("FK_Policy_UserGroup");

                    b.Navigation("IdPermissionNavigation");

                    b.Navigation("IdUserGroupNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.Seat", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.VenueAggregate.Entities.Sector", "Sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.Sector", b =>
                {
                    b.HasOne("Club25_Domain.Common.Entities.Link", "Plan")
                        .WithOne()
                        .HasForeignKey("Club25_Domain.Aggregates.VenueAggregate.Entities.Sector", "LinkId");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.Stage", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Price", null)
                        .WithMany("StageIdPriceMaxNavigations")
                        .HasForeignKey("PriceId");

                    b.HasOne("Club25_Domain.Aggregates.EventAggregate.Entities.Price", null)
                        .WithMany("StageIdPriceMinNavigations")
                        .HasForeignKey("PriceId1");

                    b.HasOne("Club25_Domain.Aggregates.VenueAggregate.Venue", "Venue")
                        .WithMany("Stages")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Club25_Domain.Aggregates.VenueAggregate.ValueObjects.VenuePriceVO", "PriceMax", b1 =>
                        {
                            b1.Property<int>("StageId")
                                .HasColumnType("int");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnOrder(6);

                            b1.Property<decimal>("Price")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnOrder(5);

                            b1.HasKey("StageId");

                            b1.ToTable("Stage");

                            b1.WithOwner()
                                .HasForeignKey("StageId");
                        });

                    b.OwnsOne("Club25_Domain.Aggregates.VenueAggregate.ValueObjects.VenuePriceVO", "PriceMin", b1 =>
                        {
                            b1.Property<int>("StageId")
                                .HasColumnType("int");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnOrder(4);

                            b1.Property<decimal>("Price")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnOrder(3);

                            b1.HasKey("StageId");

                            b1.ToTable("Stage");

                            b1.WithOwner()
                                .HasForeignKey("StageId");
                        });

                    b.Navigation("PriceMax");

                    b.Navigation("PriceMin");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.StageToStageManager", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.VenueAggregate.Entities.Stage", "Stage")
                        .WithMany("StageManagers")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Club25_Domain.Aggregates.VenueAggregate.Entities.StageManager", "StageManager")
                        .WithMany("Stages")
                        .HasForeignKey("StageManagerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Stage");

                    b.Navigation("StageManager");
                });

            modelBuilder.Entity("Club25_Domain.Common.Entities.Link", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Entities.Artist", null)
                        .WithMany("Links")
                        .HasForeignKey("ArtistId");

                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Band", null)
                        .WithMany("Links")
                        .HasForeignKey("BandId");

                    b.HasOne("Club25_Domain.Aggregates.VenueAggregate.Venue", null)
                        .WithMany("Links")
                        .HasForeignKey("VenueId");
                });

            modelBuilder.Entity("PromoterAgencyTicketAgency", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.PromoterAgencyAggregate.PromoterAgency", null)
                        .WithMany()
                        .HasForeignKey("PromoterAgenciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Club25_Domain.Aggregates.TicketAgencyAggregate.TicketAgency", null)
                        .WithMany()
                        .HasForeignKey("TicketAgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PromoterAgencyTicketAgent", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.TicketAgencyAggregate.Entities.TicketAgent", null)
                        .WithMany()
                        .HasForeignKey("AccountantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Club25_Domain.Aggregates.PromoterAgencyAggregate.PromoterAgency", null)
                        .WithMany()
                        .HasForeignKey("PromoterAgenciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SectorStage", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.VenueAggregate.Entities.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Club25_Domain.Aggregates.VenueAggregate.Entities.Stage", null)
                        .WithMany()
                        .HasForeignKey("StagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BandAggregate.Entities.ArtistDescription", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Entities.Artist", "Artist")
                        .WithMany("ArtistDescriptions")
                        .HasForeignKey("ArtistId")
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BandAggregate.Entities.BandDescription", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BandAggregate.Band", "Band")
                        .WithMany("Descriptions")
                        .HasForeignKey("BandId")
                        .IsRequired();

                    b.Navigation("Band");
                });

            modelBuilder.Entity("Club25_Domain.Common.Entities.LinkDescription", b =>
                {
                    b.HasOne("Club25_Domain.Common.Entities.Link", "Link")
                        .WithMany("LinkDescriptions")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BookingAgencyAggregate.BookingAgency", b =>
                {
                    b.OwnsOne("Club25_Domain.Aggregates.BookingAgencyAggregate.ValueObjects.BookingAgencyContactVO", "Contact", b1 =>
                        {
                            b1.Property<int>("BookingAgencyId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("country");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("phone");

                            b1.HasKey("BookingAgencyId");

                            b1.ToTable("BookingAgency");

                            b1.WithOwner()
                                .HasForeignKey("BookingAgencyId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.PromoterAgencyAggregate.PromoterAgency", b =>
                {
                    b.OwnsOne("Club25_Domain.Aggregates.PromoterAgencyAggregate.ValueObjects.PromoterAgencyContactVO", "Contact", b1 =>
                        {
                            b1.Property<int>("PromoterAgencyId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("country");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("phone");

                            b1.HasKey("PromoterAgencyId");

                            b1.ToTable("PromoterAgency");

                            b1.WithOwner()
                                .HasForeignKey("PromoterAgencyId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketAgencyAggregate.TicketAgency", b =>
                {
                    b.OwnsOne("Club25_Domain.Aggregates.TicketAgencyAggregate.ValueObjects.TicketAgencyContactVO", "Contact", b1 =>
                        {
                            b1.Property<int>("TicketAgencyId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("country");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("phone");

                            b1.HasKey("TicketAgencyId");

                            b1.ToTable("TicketAgency");

                            b1.WithOwner()
                                .HasForeignKey("TicketAgencyId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Venue", b =>
                {
                    b.OwnsOne("Club25_Domain.Aggregates.VenueAggregate.ValueObjects.VenueContactVO", "Contact", b1 =>
                        {
                            b1.Property<int>("VenueId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("country");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("phone");

                            b1.HasKey("VenueId");

                            b1.ToTable("Venue");

                            b1.WithOwner()
                                .HasForeignKey("VenueId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BookingAgencyAggregate.Entities.Booker", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.BookingAgencyAggregate.BookingAgency", "BookingAgency")
                        .WithMany("Bookers")
                        .HasForeignKey("BookingAgencyId")
                        .IsRequired();

                    b.OwnsOne("Club25_Domain.Aggregates.BookingAgencyAggregate.ValueObjects.BookingAgencyContactVO", "Contact", b1 =>
                        {
                            b1.Property<int>("BookerId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("country");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("phone");

                            b1.HasKey("BookerId");

                            b1.ToTable("Booker");

                            b1.WithOwner()
                                .HasForeignKey("BookerId");
                        });

                    b.Navigation("BookingAgency");

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.PromoterAgencyAggregate.Entities.Promoter", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.PromoterAgencyAggregate.PromoterAgency", "PromoterAgency")
                        .WithMany("Promoters")
                        .HasForeignKey("PromoterAgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Club25_Domain.Aggregates.PromoterAgencyAggregate.ValueObjects.PromoterAgencyContactVO", "Contact", b1 =>
                        {
                            b1.Property<int>("PromoterId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("country");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("phone");

                            b1.HasKey("PromoterId");

                            b1.ToTable("Promoter");

                            b1.WithOwner()
                                .HasForeignKey("PromoterId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("PromoterAgency");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketAgencyAggregate.Entities.TicketAgent", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.TicketAgencyAggregate.TicketAgency", "TicketAgency")
                        .WithMany("TicketAgents")
                        .HasForeignKey("TicketAgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Club25_Domain.Aggregates.TicketAgencyAggregate.ValueObjects.TicketAgencyContactVO", "Contact", b1 =>
                        {
                            b1.Property<int>("TicketAgentId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("country");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("phone");

                            b1.HasKey("TicketAgentId");

                            b1.ToTable("TicketAgent");

                            b1.WithOwner()
                                .HasForeignKey("TicketAgentId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("TicketAgency");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.UserAggregate.Entities.UserGroup", "IdGroupNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdGroup")
                        .IsRequired()
                        .HasConstraintName("FK_User_UserGroup");

                    b.HasOne("Club25_Domain.Aggregates.ClientAggregate.Entities.PersonObsolete", "IdPersonNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdPerson")
                        .IsRequired()
                        .HasConstraintName("FK_User_Person");

                    b.Navigation("IdGroupNavigation");

                    b.Navigation("IdPersonNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.StageManager", b =>
                {
                    b.HasOne("Club25_Domain.Aggregates.VenueAggregate.Venue", "Venue")
                        .WithMany("StageManagers")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Club25_Domain.Aggregates.VenueAggregate.ValueObjects.VenueContactVO", "Contact", b1 =>
                        {
                            b1.Property<int>("StageManagerId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("country");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)")
                                .HasColumnName("phone");

                            b1.HasKey("StageManagerId");

                            b1.ToTable("StageManager");

                            b1.WithOwner()
                                .HasForeignKey("StageManagerId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BandAggregate.Band", b =>
                {
                    b.Navigation("Bookers");

                    b.Navigation("Descriptions");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BandAggregate.Entities.Artist", b =>
                {
                    b.Navigation("ArtistDescriptions");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.ClientAggregate.Client", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.ClientAggregate.Entities.PersonObsolete", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Currency", b =>
                {
                    b.Navigation("Cultures");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Language", b =>
                {
                    b.Navigation("Cultures");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Entities.Price", b =>
                {
                    b.Navigation("ArtistIdPriceMaxNavigations");

                    b.Navigation("ArtistIdPriceMinNavigations");

                    b.Navigation("StageIdPriceMaxNavigations");

                    b.Navigation("StageIdPriceMinNavigations");

                    b.Navigation("TicketPools");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.EventAggregate.Event", b =>
                {
                    b.Navigation("TicketPools");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.TicketMediaType", b =>
                {
                    b.Navigation("TicketPools");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.TicketType", b =>
                {
                    b.Navigation("TicketPools");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.Entities.Vendor", b =>
                {
                    b.Navigation("TicketPools");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketPoolAggregate.TicketPool", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.UserAggregate.Entities.UserGroup", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.Stage", b =>
                {
                    b.Navigation("StageManagers");
                });

            modelBuilder.Entity("Club25_Domain.Common.Entities.Link", b =>
                {
                    b.Navigation("LinkDescriptions");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.BookingAgencyAggregate.BookingAgency", b =>
                {
                    b.Navigation("Bands");

                    b.Navigation("Bookers");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.PromoterAgencyAggregate.PromoterAgency", b =>
                {
                    b.Navigation("Promoters");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.TicketAgencyAggregate.TicketAgency", b =>
                {
                    b.Navigation("TicketAgents");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Links");

                    b.Navigation("StageManagers");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Club25_Domain.Aggregates.VenueAggregate.Entities.StageManager", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
