// <auto-generated />
using System;
using Infrastructure_EF_SQLdB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure_EF_SQLdB.Migrations
{
    [DbContext(typeof(Club25Context))]
    partial class Club25ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Club25_Domain.Agregates.BandAgregate.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BookingInfo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("booking_info");

                    b.Property<string>("BookingMail")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("booking_mail");

                    b.Property<string>("BookingPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("booking_phone");

                    b.Property<int?>("IdPriceMax")
                        .HasColumnType("int")
                        .HasColumnName("idPrice_max");

                    b.Property<int?>("IdPriceMin")
                        .HasColumnType("int")
                        .HasColumnName("idPrice_min");

                    b.Property<string>("Mixcloud")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("mixcloud");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("photo");

                    b.Property<string>("Soundcloud")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("soundcloud");

                    b.Property<string>("Www")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("www");

                    b.Property<string>("Youtube")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("youtube");

                    b.HasKey("Id");

                    b.HasIndex("IdPriceMax");

                    b.HasIndex("IdPriceMin");

                    b.ToTable("Artist", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.BandAgregate.Entities.ArtistDescription", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdArtist")
                        .HasColumnType("int")
                        .HasColumnName("idArtist");

                    b.Property<int>("IdLanguage")
                        .HasColumnType("int")
                        .HasColumnName("idLanguage");

                    b.HasIndex("IdArtist");

                    b.HasIndex("IdLanguage");

                    b.ToTable("ArtistDescription", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.ClientAgregate.Client", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int")
                        .HasColumnName("id_person");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("IdPerson");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.ClientAgregate.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Culture", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("IdCurrency")
                        .HasColumnType("int")
                        .HasColumnName("idCurrency");

                    b.Property<int>("IdLanguage")
                        .HasColumnType("int")
                        .HasColumnName("idLanguage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("shortName");

                    b.HasKey("Id");

                    b.HasIndex("IdCurrency");

                    b.HasIndex("IdLanguage");

                    b.ToTable("Culture", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("name");

                    b.Property<string>("Shortname")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("shortname");

                    b.HasKey("Id");

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.EventArtist", b =>
                {
                    b.Property<int>("IdArtist")
                        .HasColumnType("int")
                        .HasColumnName("idArtist");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.HasIndex("IdArtist");

                    b.HasIndex("IdEvent");

                    b.ToTable("EventArtist", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.EventDescription", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int>("IdLanguage")
                        .HasColumnType("int")
                        .HasColumnName("idLanguage");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdLanguage");

                    b.ToTable("EventDescription", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.EventMediaPartner", b =>
                {
                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int>("IdSponsor")
                        .HasColumnType("int")
                        .HasColumnName("idSponsor");

                    b.Property<int?>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdSponsor");

                    b.HasIndex("Price");

                    b.ToTable("EventMediaPartner", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.EventSponsor", b =>
                {
                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int?>("IdPrice")
                        .HasColumnType("int")
                        .HasColumnName("idPrice");

                    b.Property<int>("IdSponsor")
                        .HasColumnType("int")
                        .HasColumnName("idSponsor");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdPrice");

                    b.HasIndex("IdSponsor");

                    b.ToTable("EventSponsor", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.EventTag", b =>
                {
                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int>("IdTag")
                        .HasColumnType("int")
                        .HasColumnName("idTag");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdTag");

                    b.ToTable("EventTag", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.FeaturedEvent", b =>
                {
                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.HasIndex("IdEvent");

                    b.ToTable("FeaturedEvent", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("shortName");

                    b.HasKey("Id");

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Lineup", b =>
                {
                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("description");

                    b.Property<int?>("IdArtist")
                        .HasColumnType("int")
                        .HasColumnName("idArtist");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int?>("IdStage")
                        .HasColumnType("int")
                        .HasColumnName("idStage");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("startTime");

                    b.Property<DateTime>("StopTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("stopTime");

                    b.HasIndex("IdArtist");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdStage");

                    b.ToTable("Lineup", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int>("IdCurrency")
                        .HasColumnType("int")
                        .HasColumnName("idCurrency");

                    b.HasKey("Id");

                    b.HasIndex("IdCurrency");

                    b.ToTable("Price", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Event", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("FbEvent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fbEvent");

                    b.Property<byte[]>("Flyer")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("flyer");

                    b.Property<int>("IdVenue")
                        .HasColumnType("int")
                        .HasColumnName("idVenue");

                    b.HasKey("Id");

                    b.HasIndex("IdVenue");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.SponsorAgregate.Entities.MainSponsor", b =>
                {
                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateEnd");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateStart");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("description");

                    b.Property<int?>("IdPrice")
                        .HasColumnType("int")
                        .HasColumnName("idPrice");

                    b.Property<int>("IdSponsor")
                        .HasColumnType("int")
                        .HasColumnName("idSponsor");

                    b.HasIndex("IdPrice");

                    b.HasIndex("IdSponsor");

                    b.ToTable("MainSponsor", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.SponsorAgregate.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Details")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("details");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("email");

                    b.Property<byte[]>("Logo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("logo");

                    b.Property<byte[]>("LogoBlack")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("logoBlack");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Www")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("www");

                    b.HasKey("Id");

                    b.ToTable("Sponsor", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TagAgregate.Tag", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("hash");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("idClient");

                    b.Property<int>("IdTicketPool")
                        .HasColumnType("int")
                        .HasColumnName("idTicketPool");

                    b.Property<int?>("SeatNumber")
                        .HasColumnType("int")
                        .HasColumnName("seatNumber");

                    b.Property<DateTime>("SoldDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("soldDate");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdTicketPool");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.Entities.TicketMediaType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("TicketMediaType", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.Entities.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("TicketType", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Adres")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("adres");

                    b.Property<decimal?>("AverageProfit")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("averageProfit");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("email");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("phone");

                    b.Property<string>("Www")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("www");

                    b.HasKey("Id");

                    b.ToTable("Vendor", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.TicketPool", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateEnd");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateStart");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int")
                        .HasColumnName("idEvent");

                    b.Property<int>("IdPrice")
                        .HasColumnType("int")
                        .HasColumnName("idPrice");

                    b.Property<int>("IdTicketMedia")
                        .HasColumnType("int")
                        .HasColumnName("idTicketMedia");

                    b.Property<int>("IdTicketType")
                        .HasColumnType("int")
                        .HasColumnName("idTicketType");

                    b.Property<int>("IdVendor")
                        .HasColumnType("int")
                        .HasColumnName("idVendor");

                    b.Property<decimal?>("Profit")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("profit");

                    b.HasKey("Id");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdPrice");

                    b.HasIndex("IdTicketMedia");

                    b.HasIndex("IdTicketType");

                    b.HasIndex("IdVendor");

                    b.ToTable("TicketPool", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.UserAgregate.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.UserAgregate.Entities.Policy", b =>
                {
                    b.Property<int>("IdPermission")
                        .HasColumnType("int")
                        .HasColumnName("idPermission");

                    b.Property<int>("IdUserGroup")
                        .HasColumnType("int")
                        .HasColumnName("idUserGroup");

                    b.HasIndex("IdPermission");

                    b.HasIndex("IdUserGroup");

                    b.ToTable("Policy", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.UserAgregate.Entities.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("UserGroup", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.UserAgregate.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("IdGroup")
                        .HasColumnType("int")
                        .HasColumnName("id_group");

                    b.Property<int>("IdPerson")
                        .HasColumnType("int")
                        .HasColumnName("id_person");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("IdGroup");

                    b.HasIndex("IdPerson");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.VenueAgregate.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("IdPriceMax")
                        .HasColumnType("int")
                        .HasColumnName("idPrice_max");

                    b.Property<int?>("IdPriceMin")
                        .HasColumnType("int")
                        .HasColumnName("idPrice_min");

                    b.Property<int>("IdVenue")
                        .HasColumnType("int")
                        .HasColumnName("id_venue");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("max_capacity");

                    b.Property<int?>("MinCapacity")
                        .HasColumnType("int")
                        .HasColumnName("min_capacity");

                    b.Property<string>("Name")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IdPriceMax");

                    b.HasIndex("IdPriceMin");

                    b.HasIndex("IdVenue");

                    b.ToTable("Stage", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.VenueAgregate.Venue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("adres");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("email");

                    b.Property<decimal?>("GpsLatitude")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gps_latitude");

                    b.Property<decimal?>("GpsLongitude")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("gps_longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("phone");

                    b.Property<string>("Www")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("www");

                    b.HasKey("Id");

                    b.ToTable("Venue", (string)null);
                });

            modelBuilder.Entity("Club25_Domain.Agregates.BandAgregate.Entities.Artist", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Price", "IdPriceMaxNavigation")
                        .WithMany("ArtistIdPriceMaxNavigations")
                        .HasForeignKey("IdPriceMax")
                        .HasConstraintName("FK_Artist_Price1");

                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Price", "IdPriceMinNavigation")
                        .WithMany("ArtistIdPriceMinNavigations")
                        .HasForeignKey("IdPriceMin")
                        .HasConstraintName("FK_Artist_Price");

                    b.Navigation("IdPriceMaxNavigation");

                    b.Navigation("IdPriceMinNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.BandAgregate.Entities.ArtistDescription", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.BandAgregate.Entities.Artist", "IdArtistNavigation")
                        .WithMany()
                        .HasForeignKey("IdArtist")
                        .IsRequired()
                        .HasConstraintName("FK_ArtistDescription_Artist");

                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Language", "IdLanguageNavigation")
                        .WithMany()
                        .HasForeignKey("IdLanguage")
                        .IsRequired()
                        .HasConstraintName("FK_ArtistDescription_Language");

                    b.Navigation("IdArtistNavigation");

                    b.Navigation("IdLanguageNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.ClientAgregate.Client", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.ClientAgregate.Entities.Person", "IdPersonNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("IdPerson")
                        .IsRequired()
                        .HasConstraintName("FK_Client_Person");

                    b.Navigation("IdPersonNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Culture", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Currency", "IdCurrencyNavigation")
                        .WithMany("Cultures")
                        .HasForeignKey("IdCurrency")
                        .IsRequired()
                        .HasConstraintName("FK_Culture_Currency");

                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Language", "IdLanguageNavigation")
                        .WithMany("Cultures")
                        .HasForeignKey("IdLanguage")
                        .IsRequired()
                        .HasConstraintName("FK_Culture_Language");

                    b.Navigation("IdCurrencyNavigation");

                    b.Navigation("IdLanguageNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.EventArtist", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.BandAgregate.Entities.Artist", "IdArtistNavigation")
                        .WithMany()
                        .HasForeignKey("IdArtist")
                        .IsRequired()
                        .HasConstraintName("FK_EventArtists_Artist");

                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventArtists_Event");

                    b.Navigation("IdArtistNavigation");

                    b.Navigation("IdEventNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.EventDescription", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventDescription_Event");

                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Language", "IdLanguageNavigation")
                        .WithMany()
                        .HasForeignKey("IdLanguage")
                        .IsRequired()
                        .HasConstraintName("FK_EventDescription_Language");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdLanguageNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.EventMediaPartner", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventMediaPartner_Event");

                    b.HasOne("Club25_Domain.Agregates.SponsorAgregate.Sponsor", "IdSponsorNavigation")
                        .WithMany()
                        .HasForeignKey("IdSponsor")
                        .IsRequired()
                        .HasConstraintName("FK_EventMediaPartner_Sponsor");

                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Price", "PriceNavigation")
                        .WithMany()
                        .HasForeignKey("Price")
                        .HasConstraintName("FK_EventMediaPartner_Price");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdSponsorNavigation");

                    b.Navigation("PriceNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.EventSponsor", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventSponsor_Event");

                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Price", "IdPriceNavigation")
                        .WithMany()
                        .HasForeignKey("IdPrice")
                        .HasConstraintName("FK_EventSponsor_Price");

                    b.HasOne("Club25_Domain.Agregates.SponsorAgregate.Sponsor", "IdSponsorNavigation")
                        .WithMany()
                        .HasForeignKey("IdSponsor")
                        .IsRequired()
                        .HasConstraintName("FK_EventSponsor_Sponsor");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdPriceNavigation");

                    b.Navigation("IdSponsorNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.EventTag", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventTag_Event");

                    b.HasOne("Club25_Domain.Agregates.TagAgregate.Tag", "IdTagNavigation")
                        .WithMany()
                        .HasForeignKey("IdTag")
                        .IsRequired()
                        .HasConstraintName("FK_EventTag_Tag");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdTagNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.FeaturedEvent", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_FeaturedEvents_Event");

                    b.Navigation("IdEventNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Lineup", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.BandAgregate.Entities.Artist", "IdArtistNavigation")
                        .WithMany()
                        .HasForeignKey("IdArtist")
                        .HasConstraintName("FK_Lineup_Artist");

                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Event", "IdEventNavigation")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_Lineup_Event");

                    b.HasOne("Club25_Domain.Agregates.VenueAgregate.Entities.Stage", "IdStageNavigation")
                        .WithMany()
                        .HasForeignKey("IdStage")
                        .HasConstraintName("FK_Lineup_Stage");

                    b.Navigation("IdArtistNavigation");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdStageNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Price", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Currency", "IdCurrencyNavigation")
                        .WithMany("Prices")
                        .HasForeignKey("IdCurrency")
                        .IsRequired()
                        .HasConstraintName("FK_Price_Currency");

                    b.Navigation("IdCurrencyNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Event", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.VenueAgregate.Venue", "IdVenueNavigation")
                        .WithMany("Events")
                        .HasForeignKey("IdVenue")
                        .IsRequired()
                        .HasConstraintName("FK_Event_Venue");

                    b.Navigation("IdVenueNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.SponsorAgregate.Entities.MainSponsor", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Price", "IdPriceNavigation")
                        .WithMany()
                        .HasForeignKey("IdPrice")
                        .HasConstraintName("FK_MainSponsor_Price");

                    b.HasOne("Club25_Domain.Agregates.SponsorAgregate.Sponsor", "IdSponsorNavigation")
                        .WithMany()
                        .HasForeignKey("IdSponsor")
                        .IsRequired()
                        .HasConstraintName("FK_MainSponsor_Sponsor");

                    b.Navigation("IdPriceNavigation");

                    b.Navigation("IdSponsorNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.Entities.Ticket", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.ClientAgregate.Client", "IdClientNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Client");

                    b.HasOne("Club25_Domain.Agregates.TicketPoolAgregate.TicketPool", "IdTicketPoolNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("IdTicketPool")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_TicketPool");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdTicketPoolNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.TicketPool", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Event", "IdEventNavigation")
                        .WithMany("TicketPools")
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPool_Event");

                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Price", "IdPriceNavigation")
                        .WithMany("TicketPools")
                        .HasForeignKey("IdPrice")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPool_Price");

                    b.HasOne("Club25_Domain.Agregates.TicketPoolAgregate.Entities.TicketMediaType", "IdTicketMediaNavigation")
                        .WithMany("TicketPools")
                        .HasForeignKey("IdTicketMedia")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPool_TicketMediaType");

                    b.HasOne("Club25_Domain.Agregates.TicketPoolAgregate.Entities.TicketType", "IdTicketTypeNavigation")
                        .WithMany("TicketPools")
                        .HasForeignKey("IdTicketType")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPool_TicketType");

                    b.HasOne("Club25_Domain.Agregates.TicketPoolAgregate.Entities.Vendor", "IdVendorNavigation")
                        .WithMany("TicketPools")
                        .HasForeignKey("IdVendor")
                        .IsRequired()
                        .HasConstraintName("FK_TicketPool_Vendor");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdPriceNavigation");

                    b.Navigation("IdTicketMediaNavigation");

                    b.Navigation("IdTicketTypeNavigation");

                    b.Navigation("IdVendorNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.UserAgregate.Entities.Policy", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.UserAgregate.Entities.Permission", "IdPermissionNavigation")
                        .WithMany()
                        .HasForeignKey("IdPermission")
                        .IsRequired()
                        .HasConstraintName("FK_Policy_Permission");

                    b.HasOne("Club25_Domain.Agregates.UserAgregate.Entities.UserGroup", "IdUserGroupNavigation")
                        .WithMany()
                        .HasForeignKey("IdUserGroup")
                        .IsRequired()
                        .HasConstraintName("FK_Policy_UserGroup");

                    b.Navigation("IdPermissionNavigation");

                    b.Navigation("IdUserGroupNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.UserAgregate.User", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.UserAgregate.Entities.UserGroup", "IdGroupNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdGroup")
                        .IsRequired()
                        .HasConstraintName("FK_User_UserGroup");

                    b.HasOne("Club25_Domain.Agregates.ClientAgregate.Entities.Person", "IdPersonNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdPerson")
                        .IsRequired()
                        .HasConstraintName("FK_User_Person");

                    b.Navigation("IdGroupNavigation");

                    b.Navigation("IdPersonNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.VenueAgregate.Entities.Stage", b =>
                {
                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Price", "IdPriceMaxNavigation")
                        .WithMany("StageIdPriceMaxNavigations")
                        .HasForeignKey("IdPriceMax")
                        .HasConstraintName("FK_Stage_Price");

                    b.HasOne("Club25_Domain.Agregates.EventAgregate.Entities.Price", "IdPriceMinNavigation")
                        .WithMany("StageIdPriceMinNavigations")
                        .HasForeignKey("IdPriceMin")
                        .HasConstraintName("FK_Stage_Price1");

                    b.HasOne("Club25_Domain.Agregates.VenueAgregate.Venue", "IdVenueNavigation")
                        .WithMany("Stages")
                        .HasForeignKey("IdVenue")
                        .IsRequired()
                        .HasConstraintName("FK_Stage_Venue");

                    b.Navigation("IdPriceMaxNavigation");

                    b.Navigation("IdPriceMinNavigation");

                    b.Navigation("IdVenueNavigation");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.ClientAgregate.Client", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.ClientAgregate.Entities.Person", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Currency", b =>
                {
                    b.Navigation("Cultures");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Language", b =>
                {
                    b.Navigation("Cultures");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Entities.Price", b =>
                {
                    b.Navigation("ArtistIdPriceMaxNavigations");

                    b.Navigation("ArtistIdPriceMinNavigations");

                    b.Navigation("StageIdPriceMaxNavigations");

                    b.Navigation("StageIdPriceMinNavigations");

                    b.Navigation("TicketPools");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.EventAgregate.Event", b =>
                {
                    b.Navigation("TicketPools");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.Entities.TicketMediaType", b =>
                {
                    b.Navigation("TicketPools");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.Entities.TicketType", b =>
                {
                    b.Navigation("TicketPools");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.Entities.Vendor", b =>
                {
                    b.Navigation("TicketPools");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.TicketPoolAgregate.TicketPool", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.UserAgregate.Entities.UserGroup", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Club25_Domain.Agregates.VenueAgregate.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
